services:
  angular-app:
    build: .
    restart: always
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - angular-app
